apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: aosipenko99/nginxdocker:latest
      volumeMounts:
      - name: app
        mountPath: /app
      ports:
        - containerPort: 8000
  volumes:
    - name: app
      emptyDir: {}        
  initContainers:
  - name: init-web
    image: busybox:latest
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app        
